# Generated by Django 3.0.5 on 2020-04-05 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_filename', models.CharField(blank=True, max_length=255)),
                ('breed', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('age_letter', models.CharField(blank=True, max_length=1)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], max_length=60)),
                ('size', models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('u', 'unknown')], max_length=60)),
                ('pedigree', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=60)),
                ('fur', models.CharField(choices=[('l', 'long'), ('s', 'short')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(default='b,y,a,s', max_length=7)),
                ('gender', models.CharField(default='m,f,u', max_length=6)),
                ('size', models.CharField(default='s,m,l,xl,u', max_length=8)),
                ('pedigree', models.CharField(default='y,n', max_length=3)),
                ('fur', models.CharField(default='l,s', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('l', 'linked'), ('d', 'disliked'), ('u', 'undecided')], max_length=1)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pugorugh.Dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
