# Generated by Django 3.0.5 on 2020-04-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='fur',
            field=models.CharField(choices=[('l', 'Long'), ('s', 'Short')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Unknown')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image_filename',
            field=models.ImageField(blank=True, upload_to='images/dogs/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='pedigree',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('u', 'Unknown')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(choices=[('l', 'linked'), ('d', 'disliked')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(choices=[('b', 'Baby'), ('y', 'Young'), ('a', 'Adult'), ('s', 'Senior')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='fur',
            field=models.CharField(choices=[('l', 'Long'), ('s', 'Short')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Unknown')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='pedigree',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('u', 'Unknown')], default=None, max_length=2),
        ),
    ]
