# Generated by Django 3.0.5 on 2020-04-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(default='b,y,a,s', max_length=60),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='fur',
            field=models.CharField(default='l,s', max_length=60),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(default='m,f,u', max_length=60),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='pedigree',
            field=models.CharField(default='y,n', max_length=60),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(default='s,m,l,xl,u', max_length=60),
        ),
    ]
