# Generated by Django 3.0.5 on 2020-04-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0007_auto_20200404_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='dog',
            name='fur',
            field=models.CharField(choices=[('l', 'long'), ('s', 'short')], max_length=60),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], max_length=60),
        ),
        migrations.AlterField(
            model_name='dog',
            name='pedigree',
            field=models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=60),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('u', 'unknown')], max_length=60),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(default='b,y,a,s', max_length=4),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='fur',
            field=models.CharField(default='l,s', max_length=2),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(default='m,f,u', max_length=3),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='pedigree',
            field=models.CharField(default='y,n', max_length=2),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(default='s,m,l,xl,u', max_length=5),
        ),
    ]
