# Generated by Django 3.0.5 on 2020-04-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0008_auto_20200404_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(default='b,y,a,s', max_length=7),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='fur',
            field=models.CharField(default='l,s', max_length=3),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(default='m,f,u', max_length=6),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='pedigree',
            field=models.CharField(default='y,n', max_length=3),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(default='s,m,l,xl,u', max_length=8),
        ),
    ]
